version: "3.6"

networks:
  postgres:
    driver: bridge
  front:
    driver: bridge

services:
  postgres:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "travel"
    ports:
      - "5432:5432"
    expose:
      - "5432"
    networks:
      - postgres

  frontend:
    restart: always
    build:
      context: ./front/app
      dockerfile: Dockerfile
    volumes:
      - ./front/app:/app
    environment:
      - SERVICE_NAME=frontend
      - CHOKIDAR_USEPOLLING=true
    expose:
      - "8080"
    ports:
      - "8080:8080"
    networks:
      - front

  api:
    restart: always
    build:
      context: ./api
      dockerfile: Dockerfile
    volumes:
      - ./api:/code
    expose:
      - "8000"
    ports:
      - "8000:8000"
    networks:
      - postgres
      - front
